config/routes.rb
 Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Routes for Requests

  get '/requests/to_fulfill', to: 'requests#to_fulfill'
  post '/requests/fulfill', to: 'requests#update'
  get '/requests/show_donations', to: 'requests#index'
  post '/requests/show_donations', to: 'requests#create'

  get '/requests/requester_requests', to: 'requests#index'
  get '/requests/new_donation', to: 'requests#new'
  post '/requests/new_donation', to: 'requests#create'

  resources :donors do
    resources :requests
  end
  
  resources :requests, except: :show

  resources :users, only: [:new, :create, :edit, :update, :show]
  
  resources :requesters do
    resources :requests
  end

  # Routes for Sessions

  root 'sessions#welcome'
  # post '/create', to: 'sessions#create'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'


  match '/auth/github/callback', to: 'sessions#omnicreate', via: [:get, :post]

  # get '/auth/failure', to: 'sessions#omni_create' 
  
  match '/logout', to: 'sessions#logout', via: [:get, :post]

  # Routes for Users

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  # get '/users/:id/edit', to: 'users#edit'#, as :edit_role
  post '/users/:id', to: 'users#update'

end

app/models/request.rb
class Request < ApplicationRecord
    belongs_to :donor, optional: true
    belongs_to :requester, optional: true

    scope :has_requester, -> { where(requester_id: true) }
    scope :has_donor, -> { where(donor_id: true) }
    scope :outstanding, -> { where(fulfilled: false) }
    scope :fulfilled, -> { where(fulfilled: true) }
    

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
#   before_action :authentication_required 
  
    def new
        @request = Request.new
    end

    def create
        # binding.pry
        if request_params[:donor_id]
            @request = Request.create(request_params)
            redirect_to requests_show_donations_path(current_person)
        elsif request_params[:requester_id]
            @request = Request.create(request_params)
            redirect_to requester_requests_path(current_person)#, @request)
        else
            "ruh-roh"
            # redirect_to donor_requests_path(current_person)
        end
    end
        
    def show
        # binding.pry
        @request = Request.find_by(id: params[:id])
    end
    
    def index
        if current_requester
            @requester = Requester.find_by(user_id: current_requester.user_id)
            @requests = @requester.requests
            # redirect_to requester_requests_path(current_requester)
        elsif current_donor
            # binding.pry
            @donor = Donor.find_by(user_id: current_donor.user_id)
            @donations = @donor.requests
            @requests = Request.outstanding
# binding.pry
            # redirect_to donor_requests_path(@donor)
        else
            flash[:error] = "Sorry, we can't find requests or donations for you."
        end
    end

    def edit
        # binding.pry
        @request = Request.find_by(id: params[:id])
            if current_requester
                render 'edit_request'
            elsif current_donor
                render 'edit_donation'
            else
                redirect_to new_requests_path
            end
        end

    def update
        # binding.pry
        @request = Request.find_by(id: params[:id]) #|| Request.find_by(requester_id: params[:requester_id])
        # binding.pry
        if current_requester
            @request.update(request_params)
            # binding.pry
            redirect_to requester_requests_path(current_requester)
        elsif current_donor
            @request.update_attributes(request_params)
            redirect_to donor_request_path(@request)
        else
           "not updated"
        end
    end

    def to_fulfill
        # binding.pry
        @requests = Request.outstanding

        render '/requests/to_fulfill'
    end

    def destroy
        # binding.pry
        @request = Request.find(params[:id])
        @request.destroy!
        if current_requester
            redirect_to requester_requests_path, :notice => "Your request has been deleted."
        elsif current_donor
            redirect_to donor_requests_path,  :notice => "Your donation has been deleted."
        else
            @request.errors.full_messages each do |m|
                puts m 
            end
        end

    end
 
    private

    def request_params
        params.require(:request).permit(:name, :quantity, :measurement, :requester_id, :donor_id, :fulfilled)
    end
    
end

app/helpers/requests_helper.rb
module RequestsHelper


end

app/views/requests/_form.html.erb
<%= form_for request do |f| %>
<%= f.label :name %>
<%= f.text_field :name%>
<%= f.label :quantity%>
<%= f.number_field :quantity%>
<%= f.label :measurement%>
<%= f.text_field :measurement%>
<%= f.hidden_field :requester_id, value: current_requester.id %>
<%= f.submit %><br>
<% end %>

app/views/requests/_greeting.html.erb
<h2> <% if current_donor %>
       Hello, <%= current_donor.name %>!
    <% elsif current_requester %>
        Hello, <%= current_requester.name %>!
        <% else %>
        We don't have your name. </h2>
    <% end %>

app/views/requests/_new_donation.html.erb
<h3>What would you like to donate?</h3>

<%= form_for :request do |f| %>

<%= f.label :Item %>
<%= f.text_field :name%>
<%= f.label :quantity%>
<%= f.number_field :quantity%>
<%= f.label :measurement%>
<%= f.text_field :measurement%>
<%= f.hidden_field :donor_id, :value => current_donor.id %>
<%= f.hidden_field :fulfilled, :value => true %>
<%= f.submit %><br>
<% end %>

app/views/requests/_request.html.erb
<p><%= request.id %> | <%= link_to request.name, requester_request_path(@requester, request) %></p>

<p>Edit this request</p>

<%= render 'requests/form', request: request %>

<p><%= link_to "Delete request", requester_request_path(@requester, request), method: :delete %></p>

<hr>

app/views/requests/_requester_requests.html.erb
<br>
<% if @requests.empty? %>
  <h3> You don't have any requests yet. </h3>
<% else %>
<p>Here are your current requests:</p><br>
    <% @requests.each do |r| %>
    <% #binding.pry %>
<strong><%= r.name %></strong>:   
            <%= r.quantity %> 
            <%= r.measurement.pluralize %> 
            <% if r.fulfilled %> 
                   <ol> fullfilled</ol>
            <% else %>
                    not-fulfilled
                <%= link_to 'Edit', edit_requester_request_path(current_requester, r) %>
                <%= button_to 'Delete', [current_requester, r], method: :delete, confirm: "Are you sure?" %></ul>
            <% end %>
    <% end %>
<% end %>

app/views/requests/_requesters_requests.html.erb
<%  current_requester.requests.each do |r|%>
    <% #binding.pry%>
<ul><strong><%= r.name %></strong>:   
            <%= r.quantity %> 
            <%= r.measurement.pluralize %> 
            <% if r.fulfilled? %> 
                    fullfilled</ol>
            <% else %>
                <%= link_to 'Edit', edit_requester_request_path(current_requester, r) %>
                <%= button_to 'Delete', [current_requester, r], method: :delete, confirm: "Are you sure?" %></ul>
    <% end %>
<% end %>

app/views/requests/_show_donations.html.erb
<% #binding.pry %>

<% if @donations.empty? %>
  <h3> You haven't made any donations yet. </h3>
    <%= link_to 'Donate', new_donor_request_path(current_donor) %>
<% else %>

<h3>Here are your donations:</h3>
   
    <% @donations.each do |r|%>
    <% #binding.pry %>
    <ul><strong><%= link_to r.name, edit_donor_request_path(current_donor, r), method: :edit%></strong>: 
    <%= r.quantity %> 
    <%= r.measurement %> 
    <%= link_to 'Edit', edit_donor_request_path(current_donor, r), method: :edit %>
    <%= button_to 'Delete', [current_donor, r], method: :delete, confirm: "Are you sure?" %></ul>
    <% end %>

<% end %><br>

app/views/requests/delete.html.erb
<%= link_to "Delete", donor_request_path(@donor), :method => :delete %>

app/views/requests/edit_donation.html.erb
<h1>Edit your donation here:</h1>
<% #binding.pry %>
    <%# <%= render 'requests/form', request: @request %> 
    <% if @request.requester_id %>
    <% #binding.pry %>
        <%= @request.name %>:
        <%= @request.measurement %>
        <%= @request.quantity %>

        <%= form_for @request do |f| %>
            <%= f.label(:fulfilled, "fulfill this request") %>
            <%= f.check_box(:fulfilled) %>
            <%= f.hidden_field :donor_id, value: current_person.id %>

            <%= f.submit %><br>
            <% end %>
    
    <% else %>

        <%= form_for @request do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name%>
        <%= f.label :quantity%>
        <%= f.number_field :quantity%>
        <%= f.label :measurement%>
        <%= f.text_field :measurement%>
        <%= f.label(:fulfilled, "fulfill this request") %>
        <%= f.check_box(:fulfilled) %>
        <%= f.hidden_field :donor_id, value: current_person.id %>

        <%= f.submit %><br>
    <% end %>
<%= link_to 'Back', requests_show_donations_path(current_donor) %>
<% end %>

app/views/requests/edit_request.html.erb
<h1>Edit your request here:</h1>
<% #binding.pry %>
<%= form_for @request do |f| %>
<%= f.label :name %>
<%= f.text_field :name%>
<%= f.label :quantity%>
<%= f.number_field :quantity%>
<%= f.label :measurement%>
<%= f.text_field :measurement%>
<%= f.hidden_field :requester_id, value: current_person.id %>
<%= f.submit %><br>
<% end %>

app/views/requests/index.html.erb
<% binding.pry %>
<%= render "requests/greeting" %>
<% #binding.pry %>
<% if current_requester %>
    <%= render 'requests/requester_requests' %>
    <%= link_to 'New Request', new_requester_request_path(current_requester) %>
  
<% elsif current_donor %>
    <% #binding.pry %>
    <%= render 'requests/show_donations' %>
    <%= link_to "Requester's needs", requests_to_fulfill_path(@requests) %>
    <%= render 'requests/new_donation' %>
<% else %>
    <%= flash[:error] %>
<% end %>

app/views/requests/new.html.erb
<% if current_requester %>
    <h3>What food request would you like to make?</h3>
<% elsif current_donor %>
    <h3>What would you like to donate?</h3>
<% else %>
    request/donation greeting error
<% end %>


<%= form_for @request do |f| %>
<% #binding.pry %>
<%= f.label :name %>
<%= f.text_field :name%>
<%= f.label :quantity%>
<%= f.number_field :quantity%>
<%= f.label :measurement%>
<%= f.text_field :measurement%>
<% if current_requester %>
    <%= f.hidden_field :requester_id, :value => current_requester.id %>
<% elsif current_donor %>
    <%= f.hidden_field :donor_id, :value => current_donor.id %>
    <%= f.hidden_field :fulfilled, :value => true %>
<% else %>
    role setter error
<% end %>
<%= f.submit %><br>
<% end %>

app/views/requests/show.html.erb
<strong><%= @request.name %>: 
<%= @request.quantity %> 
<%= @request.measurement.pluralize%>,
    <% if @request.fulfilled? %>
        fulfilled
    <% else %> 
        not-fulfilled</strong>
    <% end %>

<% #binding.pry %>

<% if @donor_request = @request.donor_id %>
    <%= link_to 'Edit', edit_donor_request_path(current_person, @request) %>
    <%= button_to 'Delete', donor_request_path(@request), :method => :delete %>

<% elsif @requester_request = @request.requester_id %>
    <%= link_to 'Edit', edit_requester_request_path(current_person, @request) %>
    <%= button_to 'Delete', requester_request_path(@request), :method => :delete %>

<% else %>
    edit form or delete button error
<% end %>

<br>
<% if current_donor %>
    <%= link_to 'Back', donor_requests_path(current_donor, @request) %>
<% elsif current_requester %>
    <%= link_to 'Back', requester_requests_path(current_requester, @request) %>
<% else %>
    back button error
 <% end %>

app/views/requests/to_fulfill.html.erb
<%= link_to 'Back', donor_requests_path(current_donor) %>

<h3>Here are the requesters' needs:</h3>
    <% #binding.pry %>
        <%  @requests.each do |r|%>
        <% #binding.pry%>
        <ol><strong><%= r.name %></strong>: 
        <%= r.quantity %> 
        <%= r.measurement.pluralize %> 
        <% if r.fulfilled? %> 
            fullfilled</ol>
        <% else %>
            <%= link_to 'fulfill', edit_request_path(r), method: :edit %></ol>
        <% end %>
    <% end %>