config/routes.rb
 Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Routes for Requests

  get '/requests/to_fulfill', to: 'requests#to_fulfill'
  post '/requests/fulfill', to: 'requests#update'
  get '/requests/show_donations', to: 'requests#index'
  post '/requests/show_donations', to: 'requests#create'

  get '/requests/requester_requests', to: 'requests#index'
  get '/requests/new_donation', to: 'requests#new'
  post '/requests/new_donation', to: 'requests#create'

  resources :donors do
    resources :requests
  end
  
  resources :requests, except: :show

  resources :users, only: [:new, :create, :edit, :update, :show]
  
  resources :requesters do
    resources :requests
  end

  # Routes for Sessions

  root 'sessions#welcome'
  # post '/create', to: 'sessions#create'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'


  match '/auth/github/callback', to: 'sessions#omnicreate', via: [:get, :post]

  # get '/auth/failure', to: 'sessions#omni_create' 
  
  match '/logout', to: 'sessions#logout', via: [:get, :post]

  # Routes for Users

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  # get '/users/:id/edit', to: 'users#edit'#, as :edit_role
  post '/users/:id', to: 'users#update'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>

  </head>
  <body>
  <% #binding.pry %>
  <nav> <% if logged_in? %>
        Hello, <%= current_person.name %>! You're logged in.<br>
        <%= link_to('Log out', logout_path, method: "delete") %><br>
        <%= link_to('View my account', requests_path) %><br>
        <%= link_to('Home', root_path) %><br>
        <% else %>
        You're not logged in.<br>
        <%= link_to('Sign Up', signup_path) %><br>
        <%= link_to('Log in', login_path) %><br>
        <%= link_to('Home', root_path) %>
        <%end%>
  </nav>

  <div>
  
<br>
        <%= yield %>
<br>
<br>
      <div class="wrapper">
    
  </body><br>

      <footer class="branding">
        <br><small>&copy; 2021 <strong>Foodbank3</strong></small>
      </footer>
    </div>

    <script src="https://merriam-webster.com/assets/mw/images/article/art-wap-article-main/cornucopia-horn-of-plenty-image-1597@2x.jpg"></script>
    <!--[if lt IE 7]>
      <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
      <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
    <![endif]-->
  </body>
</html>